import type { MetadataRoute } from "next";
import { absoluteUrl } from "@/lib/seo";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/about",
          "/answers",
          "/profiles",
          "/pricing",
          "/faq",
          "/privacy",
          "/terms",
          "/data-deletion",
          "/llms.txt",
          "/llms-full.txt",
        ],
        disallow: [
          "/api/",
          "/dashboard",
          "/requests",
          "/customers",
          "/messages",
          "/upload",
          "/bookings",
          "/sync",
          "/settings",
          "/orders",
          "/payments",
          "/status",
          "/revenue",
          "/flowbuilder",
          "/ticket",
          "/tickets",
          "/track/orders",
        ],
      },
      {
        userAgent: [
          "Googlebot",
          "Bingbot",
          "Applebot",
          "Applebot-Extended",
          "GoogleOther",
          "Google-InspectionTool",
          "OAI-SearchBot",
          "GPTBot",
          "ChatGPT-User",
          "ClaudeBot",
          "Claude-SearchBot",
          "Claude-User",
          "PerplexityBot",
          "Perplexity-User",
          "Google-Extended",
          "CCBot",
          "FacebookBot",
          "meta-externalagent",
        ],
        allow: [
          "/",
          "/about",
          "/answers",
          "/profiles",
          "/pricing",
          "/faq",
          "/privacy",
          "/terms",
          "/data-deletion",
          "/llms.txt",
          "/llms-full.txt",
        ],
        disallow: [
          "/api/",
          "/dashboard",
          "/requests",
          "/customers",
          "/messages",
          "/upload",
          "/bookings",
          "/sync",
          "/settings",
          "/orders",
          "/payments",
          "/status",
          "/revenue",
          "/flowbuilder",
          "/ticket",
          "/tickets",
          "/track/orders",
        ],
      },
    ],
    sitemap: absoluteUrl("/sitemap.xml"),
    host: "https://concierge.escal8.tech",
  };
}
